name: game
description: Neon-Quadrants-The-Purple-City
version: 0.0.5
repository: https://github.com/zokis/Neon-Quadrants-The-Purple-City

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.0
